log:
  level: INFO

accesslog:
  format: common

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    network: traefik
    exposedbydefault: false
  file:
    directory: /etc/traefik/config

certificatesResolvers:
  letsencrypt:
    acme:
      email: "YOUR EMAIL" # change it
      storage: acme.json
      httpChallenge:
        entryPoint: web